name: flutter_ocr_plugin
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/HenryPO/FlutterOcrPlugin.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
  test_coverage: ^0.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.u95shuke.ocr.flutter_ocr_plugin
        pluginClass: FlutterOcrPlugin
      ios:
        pluginClass: FlutterOcrPlugin

